apiVersion: v2
name: clustregcred-operator
description: A Kubernetes Operator for syncing image pull secrets across namespaces
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - kubernetes
  - operator
  - secret
  - registry
  - image-pull-secret
home: https://github.com/maozi/clustregcred-operator
maintainers:
  - name: maozi
    email: maozi@example.com