---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustregcred-operator-manager-role
rules:
  # ClustRegCred permissions
  - apiGroups:
      - grid.maozi.io
    resources:
      - clustregcreds
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - grid.maozi.io
    resources:
      - clustregcreds/finalizers
    verbs:
      - update
  - apiGroups:
      - grid.maozi.io
    resources:
      - clustregcreds/status
    verbs:
      - get
      - patch
      - update
  # Namespace permissions
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  # Secret permissions
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch